# .github/workflows/deploy.yml

name: Deploy Hugo site to GitHub Pages

on:
  # Executa em pushes na branch main
  push:
    branches: ["main"]

  # Permite execução manual no Actions tab
  workflow_dispatch:

# Permissões necessárias para o GITHUB_TOKEN fazer deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Só permite um deploy por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default para bash
defaults:
  run:
    shell: bash

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.7
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history para .GitInfo e .Lastmod
          submodules: recursive

      - name: Setup Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc --minify \
            --baseURL "https://ramos902.github.io/RamosBlog-Hextra/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Job de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
